[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "tasks"
author = "silence"

[tool.pytest.ini_options]
markers = [
    "smoke",
    "get"
]